# Generated by Django 4.1.2 on 2022-11-27 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatchReceipt',
            fields=[
                ('catchReceipt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, default='جدة', help_text=' المصدر', max_length=225)),
                ('destination', models.CharField(blank=True, default='الرياض', help_text=' الوجهة', max_length=225)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text=' التاريخ')),
                ('amount', models.CharField(help_text=' الاجرة', max_length=225)),
                ('overnight', models.CharField(default='0', help_text=' المبات', max_length=225)),
                ('return_fare', models.CharField(default='0', help_text=' اجرة رجعة', max_length=225)),
                ('deduction', models.CharField(default='0', help_text='خصم', max_length=225)),
                ('total_amount', models.CharField(blank=True, default='0', help_text='المجموع', max_length=225, null=True)),
                ('policy_number', models.CharField(blank=True, default='', help_text=' رقم البوليصة', max_length=225)),
                ('notice_number', models.CharField(blank=True, default='', help_text=' رقم الاشعار', max_length=225)),
                ('Shipment_id', models.CharField(blank=True, default='', help_text=' رقم الشحن', max_length=225)),
                ('accountant', models.CharField(help_text=' المحاسب ', max_length=225, null=True)),
                ('Vehicle_Type', models.CharField(blank=True, choices=[('تريلا براد', 'تريلا براد'), ('سطحة', 'سطحة'), ('جوانب عالي', 'جوانب عالي'), ('ستارة', 'ستارة'), ('لوري عادي', 'لوري عادي'), ('لوري براد', 'يدنة عادي'), ('يدنة عادي', 'يدنة عادي'), ('دينة براد', 'دينة براد')], default='سطحة', help_text='نوع السيارة(سطحة - جوانب) ....', max_length=30, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companymodel')),
                ('delegate', models.ForeignKey(help_text=' المندوب ', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivermodel')),
            ],
        ),
    ]
