# Generated by Django 4.1.2 on 2022-11-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('driver_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(blank=True, help_text='اسم السائق', max_length=225, null=True)),
                ('driver_nationality', models.CharField(blank=True, choices=[('Saudi', 'Saudi'), ('Yemeni', 'Yemeni'), ('Syrian', 'Syrian'), ('Egypt', 'Egypt'), ('Afghanistan', 'Afghanistan'), ('Pakistani', 'Pakistani'), ('Jordanian', 'Jordanian'), ('Indian', 'Indian'), ('other', 'other')], default='other', help_text='جنسية السائق', max_length=20, null=True)),
                ('driver_phone_number', models.CharField(blank=True, help_text='رقم هاتف السائق ', max_length=16, null=True)),
                ('Identification_Number', models.CharField(blank=True, help_text='رقم الهوية/الاقامة', max_length=10, null=True)),
                ('truck_plate_number', models.CharField(blank=True, help_text='رقم لوحة الشاحنة', max_length=8, null=True)),
                ('Vehicle_Type', models.CharField(blank=True, choices=[('تريلا براد', 'تريلا براد'), ('سطحة', 'سطحة'), ('جوانب عالي', 'جوانب عالي'), ('ستارة', 'ستارة'), ('لوري عادي', 'لوري عادي'), ('لوري براد', 'يدنة عادي'), ('يدنة عادي', 'يدنة عادي'), ('دينة براد', 'دينة براد')], default='سطحة', help_text='نوع السيارة(سطحة - جوانب) ....', max_length=30, null=True)),
                ('Sequence_Number', models.CharField(blank=True, help_text='الرقم التسلسلي من الاستمارة', max_length=30, null=True)),
                ('Owner_car_id_number', models.CharField(blank=True, help_text='رقم هوية مالك السيارة', max_length=10, null=True)),
            ],
        ),
    ]
