# Generated by Django 4.1.2 on 2022-11-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('company_name', models.CharField(help_text='اسم الشركة', max_length=225)),
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_city', models.CharField(default='Dammam', help_text='مقر الشركة', max_length=225)),
                ('charging_area', models.CharField(default='Jeddah', help_text='منطقة الشحن ', max_length=225)),
            ],
        ),
    ]
